apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: appgrupo1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: appgrupo1
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50