apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grupo1-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: appgrupo1-service
              servicePort: 80    
